name: notesync
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  lottie: ^3.3.1
  animated_splash_screen: ^1.2.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  google_sign_in: ^6.1.4
  path_provider: ^2.1.5
  flutter_web_auth: ^0.6.0
  url_launcher: ^6.3.1
  # speech_to_text: ^6.3.0  # Temporarily commented out

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/
